
services:
  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "9803:9803"  # mongodbTaskFlow - PHP 8.3
      - "9802:9802"  # task_flow - PHP 8.2
      - "9998:9998"  # test-12 - PHP 8.2
      - "9999:9999"  # designPatterns - PHP 8.2
      - "8000:8000" # cb_portal_api - PHP 8.2
      - "9193:9193" # retail_admin - PHP 5.6
      - "9608:9608" # admin_hcvn - PHP 8.1
      - "8686:8686" # erp - PHP 7.4
      - "8080:8080" # b2bApi - PHP 8.2
      - "8704:8704" # cb_admin_api - PHP 8.2
      - "8181:8181" # baokim_landing_page - PHP 8.2
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./projects:/var/www/projects
    depends_on:
      - php82
    networks:
      - app-network


  # PHP 8.3 Service
  # php83:
  #   build:
  #     context: ./php-versions/php83
  #     dockerfile: Dockerfile
  #   container_name: php83
  #   restart: unless-stopped
  #   volumes:
  #     - ./projects:/var/www/projects
  #   networks:
  #     - app-network

  # PHP 8.2 Service
  php82:
    build:
      context: ./php-versions/php82
      dockerfile: Dockerfile
    container_name: php82
    restart: unless-stopped
    volumes:
      - ./projects:/var/www/projects
    networks:
      - app-network

  php74:
    build:
      context: ./php-versions/php74
      dockerfile: Dockerfile
    container_name: php74
    restart: unless-stopped
    volumes:
      - ./projects:/var/www/projects
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --bind-address=0.0.0.0
    restart: unless-stopped
    networks:
      - app-network

  # mongo:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   networks:
  #     - app-network

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #     ME_CONFIG_BASICAUTH: false
  #   networks:
  #     - app-network


networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
